package com.crossover.techtrial.service;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import com.crossover.techtrial.model.HourlyElectricity;
import com.crossover.techtrial.model.Panel;
import com.crossover.techtrial.repository.HourlyElectricityRepository;
import com.crossover.techtrial.service.exception.ResourceNotFoundException;

/**
 * HourlyElectricityServiceImpl will handle electricity generated by a Panel.
 *
 * @author Crossover
 *
 */

@Service
public class HourlyElectricityServiceImpl implements HourlyElectricityService {
	
	@Autowired
	HourlyElectricityRepository hourlyElectricityRepository;
	
	@Autowired
	PanelService panelService;
	    
	public HourlyElectricity save(HourlyElectricity hourlyElectricity, String panelSerial) {
		Panel panel = panelService.findBySerial(panelSerial);
		hourlyElectricity.setPanel(panel);
		return hourlyElectricityRepository.save(hourlyElectricity);
	}

	public Page<HourlyElectricity> getAllHourlyElectricityByPanelId(String panelSerial, Pageable pageable) {
		Panel panel = panelService.findBySerial(panelSerial);
		if(panel == null)
			throw new ResourceNotFoundException(String.format("There is no electricity for panel {}", panelSerial));
		return hourlyElectricityRepository.findAllByPanelIdOrderByReadingAtDesc(panel.getId(), pageable);
	}

	@Override
	public List<HourlyElectricity> getAllHourlyElectricityByReadingAtBetween(LocalDate date,Panel panel) {
		return hourlyElectricityRepository.findByReadingAtBetweenAndPanel(date.atStartOfDay(), date.atTime(LocalTime.MAX), panel);
	}

}