package com.crossover.techtrial.model;

import java.io.Serializable;
import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * DailyElectricity is responsible for electricity generated by a Panel in an hour.
 * 
 * @author Jonas Arioli
 *
 */


@Entity
@Table(name = "daily_electricity")
public class DailyElectricity implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@JsonIgnore
	@ManyToOne
	@JoinColumn(name = "panel_id", referencedColumnName = "id")
	Panel panel;

	@Column(name = "daily_sum")
	Long dailySum;

	@Column(name = "daily_min")
	Long dailyMin;

	@Column(name = "daily_max")
	Long dailyMax;

	@Column(name = "daily_average")
	Double dailyAverage;
	
	@Column(name = "date")
	LocalDate date;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Panel getPanel() {
		return panel;
	}

	public void setPanel(Panel panel) {
		this.panel = panel;
	}

	public Long getDailySum() {
		return dailySum;
	}

	public void setDailySum(Long dailySum) {
		this.dailySum = dailySum;
	}

	public Long getDailyMin() {
		return dailyMin;
	}

	public void setDailyMin(Long dailyMin) {
		this.dailyMin = dailyMin;
	}

	public Long getDailyMax() {
		return dailyMax;
	}

	public void setDailyMax(Long dailyMax) {
		this.dailyMax = dailyMax;
	}

	public Double getDailyAverage() {
		return dailyAverage;
	}

	public void setDailyAverage(Double dailyAverage) {
		this.dailyAverage = dailyAverage;
	}
	
	public LocalDate getDate() {
		return date;
	}

	public void setDate(LocalDate date) {
		this.date = date;
	}

}
